version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for
      # this Jupyter Book so it builds.
      - "jupyter-book config sphinx docs/"

# Dependencies required to build your docs
python:
   install:
     - requirements: requirements.txt
     - method: pip
       path: .
       extra_requirements:
         - sphinx
#     - pip:
#       - jupyter-book

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true