---
title: "Disaster Prepositioning Case Study"
author: "Your Name"
repository: https://github.com/yurchisin/disaster_prepositioning
binder:
  url: "https://mybinder.org"
execute:
  execute_notebooks: "force"
