---
title: "Disaster Prepositioning Case Study"
author: "Gurobi Optimization"
repository: https://github.com/yurchisin/disaster_prepositioning/
binder:
  url: "https://mybinder.org"
execute:
  execute_notebooks: "force"
sphinx:
  config:
    html_static_path: ["_static"]
    html_css_files: ["custom.css"]
