[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "disaster_prepositioning"

[project.optional-dependencies]
sphinx = ["jupyter-book[sphinx]>=1.0"]
