---
title: "Disaster Prepositioning Case Study"
author: "Gurobi Optimization"
copyright: "2025, Gurobi Optimization, LLC"
repository: 
  url: https://github.com/yurchisin/disaster_prepositioning/

binder:
  url: "https://mybinder.org"
execute:
  execute_notebooks: "force"
sphinx:
  config:
    master_doc: content/intro
    html_static_path: ["_static"]
    html_css_files: ["custom.css"]
